app.eureka-server: localhost

server:
  port: 9090

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400
---
app.eureka-server: discovery-server

spring:
  config:
    activate:
      on-profile: docker