app:
  eureka-server: localhost
  auth-server: localhost

server.port: 8443

server.ssl:
  key-store-type: PKCS12
  key-store: classpath:keystore/gateway.p12
  key-store-password: password
  key-alias: localhost

spring:
  security.oauth2.resourceserver.jwt.issuer-uri: http://${app.auth-server}:9999
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: oauth-server
          uri: lb://authorization-server
          predicates:
            - Path=/oauth2/**

        - id: eureka-api
          uri: http://${app.eureka-server}:8061
          predicates:
            - Path=/eureka/api/{segment}
          filters:
            - SetPath=/eureka/{segment}

        - id: eureka-web-start
          uri: http://${app.eureka-server}:8061
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: eureka-web-other
          uri: http://${app.eureka-server}:8061
          predicates:
            - Path=/eureka/**

        - id: config-server
          uri: http://${app.config-server}:8888
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config/(?<segment>.*), /$\{segment}

        - id: payment-api-service
          uri: lb://payment-api-service
          predicates:
            - Path=/payment/**

        - id: merchant-api-service
          uri: lb://merchant-api-service
          predicates:
            - Path=/merchant/**

        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
---
app:
  eureka-server: discovery-server
  auth-server: authorization-server

spring:
  config:
    activate:
      on-profile: docker