app.eureka-server: localhost

server:
  port: 10010

springdoc:
  packagesToScan: ea.slartibartfast.payment
---
app.eureka-server: discovery-server

spring:
  config:
    activate:
      on-profile: docker