app:
  eureka-server: localhost
  auth-server: localhost

server:
  port: 10010

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://${app.auth-server}:9999

springdoc:
  packagesToScan: ea.slartibartfast.payment
---
app:
  eureka-server: discovery-server
  auth-server: authorization-server

spring:
  config:
    activate:
      on-profile: docker