apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kibana-gateway
  namespace: logging
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "kibana.kubernetes.docker.internal"
      port:
        number: 443
        name: https-tracing
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: slartibartfast-certificate
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kibana-vs
  namespace: logging
spec:
  hosts:
    - "kibana.kubernetes.docker.internal"
  gateways:
    - kibana-gateway
  http:
    - route:
        - destination:
            host: kibana
            port:
              number: 5601
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kibana
  namespace: logging
spec:
  host: kibana
  trafficPolicy:
    tls:
      mode: DISABLE