version: '2.1'

services:
  payment-api:
    build: microservices/payment-api-service
    mem_limit: 350m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  card-api:
    build: microservices/card-api-service
    mem_limit: 350m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  auth-api:
    build: spring-cloud/auth-api-service
    mem_limit: 350m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  merchant-api:
    build: microservices/merchant-api-service
    mem_limit: 350m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    build: spring-cloud/gateway-server
    mem_limit: 350m
    ports:
      - "8060:8060"
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  discovery-server:
    build: spring-cloud/discovery-server
    mem_limit: 350m
    ports:
      - "8061:8061"
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  config-server:
    build: spring-cloud/config-server
    mem_limit: 350m
    ports:
      - "8888:8888"
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=native

networks:
  my-network:
    name: my-network