version: '2.1'

services:
  payment-api:
    build: microservices/payment-api-service
    image: slartibartfast/payment-api-service
    mem_limit: 350m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  card-api:
    build: microservices/card-api-service
    image: slartibartfast/card-api-service
    mem_limit: 350m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  merchant-api:
    build: microservices/merchant-api-service
    image: slartibartfast/merchant-api-service
    mem_limit: 350m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway-server:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_SSL_KEY_STORE=file:/keystore/gateway.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=password
    volumes:
      - $PWD/keystore:/keystore
    build: spring-cloud/gateway-server
    image: slartibartfast/gateway-server
    mem_limit: 350m
    ports:
      - "8443:8443"
    networks:
      - my-network

  config-server:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,native
      - ENCRYPT_KEY=${CONFIG_SERVER_ENCRYPT_KEY}
    volumes:
      - $PWD/config-repo:/config-repo
    build: spring-cloud/config-server
    image: slartibartfast/config-server
    mem_limit: 350m
    networks:
      - my-network

  authorization-server:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: spring-cloud/authorization-server
    image: slartibartfast/auth-server
    mem_limit: 350m
    networks:
      - my-network

networks:
  my-network:
    name: my-network