version: '2.1'

services:
  payment-api:
    build: payment-api-service
    mem_limit: 350m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  card-api:
    build: card-api-service
    mem_limit: 350m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  auth-api:
    build: auth-api-service
    mem_limit: 350m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  merchant-api:
    build: merchant-api-service
    mem_limit: 350m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    build: gateway-server
    mem_limit: 350m
    ports:
      - "8060:8060"
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  discovery-server:
    build: discovery-server
    mem_limit: 350m
    ports:
      - "8061:8061"
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  config-server:
    build: config-server
    mem_limit: 350m
    ports:
      - "8888:8888"
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=native

networks:
  my-network:
    name: my-network