version: '2.1'

services:
  payment-api:
    build: microservices/payment-api-service
    mem_limit: 350m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  card-api:
    build: microservices/card-api-service
    mem_limit: 350m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  auth-api:
    build: spring-cloud/auth-api-service
    mem_limit: 350m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  merchant-api:
    build: microservices/merchant-api-service
    mem_limit: 350m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_SSL_KEY_STORE=file:/keystore/gateway.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=password
    volumes:
      - $PWD/keystore:/keystore
    build: spring-cloud/gateway-server
    mem_limit: 350m
    ports:
      - "8443:8443"
    networks:
      - my-network

  discovery-server:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: spring-cloud/discovery-server
    mem_limit: 350m
    networks:
      - my-network

  config-server:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,native
    volumes:
      - $PWD/config-repo:/config-repo
    build: spring-cloud/config-server
    mem_limit: 350m
    networks:
      - my-network


networks:
  my-network:
    name: my-network