apiVersion: v2
name: prod-env
description: A Helm chart for Demo Spring Cloud Microservices running in a Prod Environment
version: 1.0.0
appVersion: "1.16.0"

dependencies:

  - name: common
    version: 1.0.0
    repository: file://../../common

  - name: authorization-server
    version: 1.0.0
    repository: file://../../components/authorization-server

  - name: card-api-service
    version: 1.0.0
    repository: file://../../components/card-api-service

  - name: merchant-api-service
    version: 1.0.0
    repository: file://../../components/merchant-api-service

  - name: payment-api-service
    version: 1.0.0
    repository: file://../../components/payment-api-service
