gateway:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,prod"
  resources:
    requests:
      memory: 200Mi
    limits:
      memory: 400Mi

auth-server:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,prod"
  resources:
    requests:
      memory: 200Mi
    limits:
      memory: 400Mi

card-api:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,prod"
  resources:
    requests:
      memory: 200Mi
    limits:
      memory: 400Mi

merchant-api:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,prod"
  resources:
    requests:
      memory: 200Mi
    limits:
      memory: 400Mi

payment-api:
  image:
    tag: v1
  env:
    SPRING_PROFILES_ACTIVE: "docker,prod"
  resources:
    requests:
      memory: 200Mi
    limits:
      memory: 400Mi