server.port: 8888
spring:
  profiles:
    active: native
  application.name: config-server
  cloud:
    config:
      override-system-properties: false
      server:
        native:
          search-locations:
            classpath:/config/