rabbitmq-server: 127.0.0.1

server:
  port: 8061

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  rabbitmq:
    host: ${rabbitmq-server}
    port: 5672
    username: guest
    password: guest
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0

---
rabbitmq-server: rabbitmq

spring:
  config:
    activate:
      on-profile: docker