server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment-api-service
          uri: lb://payment-api-service
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment/(?<path>.*), /$\{path}
            - CustomGatewayFilter
        - id: card-api-service
          uri: lb://card-api-service
          predicates:
            - Path=/card/**
          filters:
            - RewritePath=/card/(?<path>.*), /$\{path}
        - id: merchant-api-service
          uri: lb://merchant-api-service
          predicates:
            - Path=/merchant/**
          filters:
            - RewritePath=/merchant/(?<path>.*), /$\{path}
        - id: auth-api-service
          uri: lb://auth-api-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs