app.config-server: localhost
app.eureka-server: localhost
rabbitmq-server: 127.0.0.1

server:
  port: 8060

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment-api-service
          uri: lb://payment-api-service
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1
            - CustomGatewayFilter
        - id: card-api-service
          uri: lb://card-api-service
          predicates:
            - Path=/card/**
          filters:
            - StripPrefix=1
            - CustomGatewayFilter
        - id: merchant-api-service
          uri: lb://merchant-api-service
          predicates:
            - Path=/merchant/**
          filters:
            - StripPrefix=1
        - id: auth-api-service
          uri: lb://auth-api-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

  rabbitmq:
    host: ${rabbitmq-server}
    port: 5672
    username: guest
    password: guest
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0

---
app.config-server: config-server
app.eureka-server: discovery-server
rabbitmq-server: rabbitmq

spring:
  config:
    activate:
      on-profile: docker