app.eureka-server: localhost
rabbitmq-server: 127.0.0.1

server:
  port: 7002

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-server}:8061/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: ea.slartibarfast.payment

spring:
  rabbitmq:
    host: ${rabbitmq-server}
    port: 5672
    username: guest
    password: guest
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0

---
app.eureka-server: discovery-server
rabbitmq-server: rabbitmq

spring:
  config:
    activate:
      on-profile: docker