apiVersion: v2
name: payment-api
description: A Helm chart for the payment API
type: application
version: 1.0.0
appVersion: "1.16.0"

dependencies:
  - name: common
    version: 1.0.0
    repository: file://../../common
